<a href="https://colab.research.google.com/github/chanxxw/AI_Medical_Practice/blob/main/Introduction_to_Tensors_for_Medical_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# 데이터로부터 직접 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# Numpy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 다른 텐서로부터 생성
x_ones = torch.ones_like(x_data)  # x_data의 속성을 유지
print(f"Ones Tensor: \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data의 속성을 덮어씀
print(f"Random Tensor: \n{x_rand} \n")

# 무작위 또는 상수 값 사용
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor} \n")
print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor}")


Ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
tensor([[0.5158, 0.2369],
        [0.6918, 0.9882]]) 

Random Tensor: 
tensor([[0.8988, 0.8348, 0.1392],
        [0.2799, 0.3800, 0.8909]]) 

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 텐서의 속성
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

# Numpy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print(t2)

# tensor.T 는 텐서의 전치(transpose)를 반환
# 전치 : 행렬의 가로세로를 바꿔주는 것
print(tensor.T)

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산
# torch.matmul : 행렬 곱 (Matrix Multiplication) 선형대수에서 말하는 행렬 간의 곱을 의미.
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)

# 요소별 곱(element-wise product)을 계산
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
# torch.mul (또는 * 연산자) : 원소별 곱 (Element-wise Multiplication), 텐서의 같은 위치에 있는 원소끼리 곱함
print(z2)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[3., 3., 3., 3.],
   

In [ ]:
# 텐서를 Numpy 배열로 변환하기
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# 텐서의 변경 사항 Numpy 반영
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

# Numpy 배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)

# Numpy 변경 사항 텐서에 반영
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

# GPU로 보낸 텐서에서의 결과
if torch.cuda.is_available():
    t = t.to("cuda")
    t.add_(1)
    print(f"t: {t}")
    print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
t: tensor([3., 3., 3., 3., 3.], device='cuda:0', dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
